repository_type: pipeline
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-mikrokondo_logo_light.png
    - docs/images/nf-core-mikrokondo_logo_light.png
    - docs/images/nf-core-mikrokondo_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - docs/output.md
    - docs/README.md
    - docs/usage.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
    - assets/multiqc_config.yml
  files_unchanged:
    - LICENSE
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - .gitignore
  schema_params:
template:
  prefix: phac-nml
