repository_type: pipeline
nf_core_version: "3.4.1"
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-mikrokondo_logo_light.png
    - docs/images/nf-core-mikrokondo_logo_light.png
    - docs/images/nf-core-mikrokondo_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - docs/output.md
    - docs/README.md
    - docs/usage.md
    - conf/igenomes_ignored.config
    - ro-crate-metadata.json
  files_unchanged:
    - LICENSE
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - .gitignore
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - params.max_cpus
    - params.max_memory
    - params.max_time
  multiqc_config: False
  nf_test_content:
    - tests/main.nf.test
template:
  prefix: phac-nml
  name: mikrokondo
  description: Mikrokondo Pipeline
  version: 0.9.5
  outdir: .
  is_nfcore: false
