matrix:
- name: Markdown
  sources:
  - '!venv/**/*.md|**/*.md'
  default_encoding: utf-8
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
    wordlists:
    - .wordlist.txt
  pipeline:
  - pyspelling.filters.context:
    - open: ''
    - close:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
      - pymdownx.striphtml
      - markdown.extensions.toc:
          slugify: !!python/name:pymdownx.slugs.uslugify
          permalink: "\ue157"
      - markdown.extensions.admonition
      - markdown.extensions.smarty
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
      - small
