matrix:
- name: Markdown
  sources:
  - '!venv/**/*.md|**/*.md'
  default_encoding: utf-8
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    encoding: utf-8
    wordlists:
    - .wordlist.txt
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
      - pymdownx.striphtml
      - pymdownx.blocks
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
      - small
